import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Demo</title>
        <meta name="description" content="Generated by nelsonfr.dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Next Demo deployed in EC2 AWS</h1>
      </main>
    </div>
  )
}

export default Home
